### PR TITLE
Make sure preference key value is not empty.

### LINKED ISSUE #64: Caused by: java.lang.IllegalArgumentException: Query is not supported for Uri:
Caused by: java.lang.IllegalArgumentException: Query is not supported for Uri: content://com.sankuai.meituan.dispatch.crowdsource.tray/preferences/com.sankuai.meituan.xxxxx/xxxxxxxe.mark?backup=true
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:413)
	at android.content.ContentResolver.query(ContentResolver.java:461)
	at android.content.ContentResolver.query(ContentResolver.java:404)
	at net.grandcentrix.tray.provider.TrayProviderHelper.a(ProGuard:141)
	at net.grandcentrix.tray.provider.ContentProviderStorage.a(ProGuard:2172)
	at net.grandcentrix.tray.core.Preferences.a(ProGuard:68)
	at com.meituan.xxx.util.SPUtil.a(ProGuard:1118)
	at com.meituan.xxx.util.SPUtil.a(ProGuard:25)

### PR DESCRIPTION
**Pull request by eyedol**
Fixes #64 

This `PR` makes the following changes:
- When a preference key is empty, an `illegalArgumentException` is
    thrown. This prevents empty string being passed to the underling storage
    engine from throwing an error with an unclear message.
- Add tests for this fix.

### CODE REVIEW

**Comment by passsy** [comment]
LGTM 🚢

File: library/src/main/java/net/grandcentrix/tray/core/Preferences.java [hunk 1]
```diff
@@ -301,4 +302,11 @@ static boolean isDataTypeSupported(final Object data) {
                 || data instanceof Boolean
                 || data == null;
     }
+
+    boolean putData(String key, Object value) {
```
Comment (StefMa) [inline library/src/main/java/net/grandcentrix/tray/core/Preferences.java]: Why is putData not `private`?

Comment (eyedol) [inline library/src/main/java/net/grandcentrix/tray/core/Preferences.java]: @StefMa I was thinking it will be reusable by subclasses in the package. I can make it private if it makes more sense that way.

**Comment by eyedol** [comment]
@jreehuis  updated the `JavaDoc` per your request

File: library/src/main/java/net/grandcentrix/tray/core/Preferences.java (hunk 1 above)
Comment (jreehuis) [inline library/src/main/java/net/grandcentrix/tray/core/Preferences.java]: If it should be accessible from any other class like subclasses, than I am missing the check if the version was upgraded and an appropriate logging.
I would just make it `private`.

Comment (eyedol) [inline library/src/main/java/net/grandcentrix/tray/core/Preferences.java]: Made private with the latest commit.
